name: AI Search CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # See explanation: https://github.com/orgs/community/discussions/25678 
      - name: Clean disk
        run: |
          rm -rf /opt/hostedtoolcache
                
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: ai-search-demo
          push: true
          tags: ghcr.io/kyryl-opens-ml/smart-hr-ai-search:latest
          cache-from: type=registry,ref=ghcr.io/kyryl-opens-ml/smart-hr-ai-search:buildcache
          cache-to: type=registry,ref=ghcr.io/kyryl-opens-ml/smart-hr-ai-search:buildcache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: [docker-build]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Railway
        run: rm -rf package-lock.json && npm i -g @railway/cli

      - name: Deploy
        run: railway redeploy --service app --yes
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
